### ISSUE TITLE
unable to purge control measures associated with a strategy

### ISSUE THREAD

**Issue by cseppan** [USEPA-OAQPS/emf#14]
Trying to remove temporary "Copy of ..." measures from EPA server. Changed all to temp sector "asm_backup". Imported empty CSVs and set sector to Purge. Error when trying to finalize strategies.
```
gov.epa.emissions.framework.services.EmfException: Cannot update without owning lock
	at gov.epa.emissions.framework.services.persistence.LockingScheme.doUpdate(LockingScheme.java:90)
	at gov.epa.emissions.framework.services.persistence.LockingScheme.renewLockOnUpdate(LockingScheme.java:97)
	at gov.epa.emissions.framework.services.cost.ControlStrategyDAO.updateWithLock(ControlStrategyDAO.java:187)
	at gov.epa.emissions.framework.services.cost.ControlStrategyDAO.finalizeControlStrategy(ControlStrategyDAO.java:536)
	at gov.epa.emissions.framework.services.cost.controlmeasure.io.CMImportTask.run(CMImportTask.java:118)
	at gov.epa.emissions.framework.services.GCEnforcerTask.run(GCEnforcerTask.java:23)
	at EDU.oswego.cs.dl.util.concurrent.PooledExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by cseppan** [comment]
The control strategy was never actually locked before trying to do the update (which expected a lock to already be in place). Fixed in commit 9eac2fa.
